"use client"; // Add this directive at the top
import { Inter } from "next/font/google";
import Header from "../../components/header"; // Note: Ensure correct case for 'Header'
import Footer from "../../components/footer";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "../../public/styles/bootstrap-variables.scss";
import "@fortawesome/fontawesome-free/css/all.min.css";
// import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
// import { faSearch } from '@fortawesome/free-solid-svg-icons';

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Eudoxus+Sans:wght@400;700&display=swap"
          rel="stylesheet"
        />
        <style>
          {`
              @font-face {
                font-family: 'Eudoxus Sans';
                src: url('/fonts/eudoxus-sans.woff2') format('woff2'),
                     url('/fonts/eudoxus-sans.woff') format('woff');
                font-weight: 400;
                font-style: normal;
              }
              @font-face {
                font-family: 'Eudoxus Sans';
                src: url('/fonts/eudoxus-sans-bold.woff2') format('woff2'),
                     url('/fonts/eudoxus-sans-bold.woff') format('woff');
                font-weight: 700;
                font-style: normal;
              }
            `}
        </style>
      </head>
      <body className={inter.className}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
